apiVersion: v1
kind: Namespace
metadata:
  name: openshift-compliance
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: compliance-operator
  namespace: openshift-compliance
spec:
  targetNamespaces:
    - openshift-compliance
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: compliance-operator
  namespace: openshift-compliance
spec:
<<<<<<< HEAD
  channel: stable           # ajusta según canal que usen en tu cluster
=======
  channel: stable
>>>>>>> 150bcca33d1bbabb2242a821aad1c7c4d43e8f50
  name: compliance-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace

